### ISSUE TITLE
Add Figma Flowdock integration

### ISSUE THREAD

**Issue by kb0rg** [thesis/heimdall#118]
Incorporate Figma comments into Flowdock, with the following requirements

- Figma projects can be associated with specific Flowdock channels
- Comments start their own thread
- Provide direct link to open in app or browser
- Show full comment & user who posted
- Avatar is distinct for users to identify as a Figma comment (ie, Figma logo)
- Bonus (nice to have, not requirement): link user from Figma with tag in Flowdock

See suggestion threads [here](https://www.flowdock.com/app/cardforcoin/playground/threads/ycDpwWtq158IlMoYocBrBBp4XbM) and [here](https://www.flowdock.com/app/cardforcoin/bifrost/threads/gwUL0L4MFEz2GbAsc7fNyw0J0To) for possible additional context.

Further investigation into the Figma webhooks and/or API required to assess whether current requirements need adjustment. 

This may need to be broken into smaller issues.

**Comment by Shadowfiend** [comment]
Flowdock is no longer on the radar, so closing this for now.
