### ISSUE TITLE
Timed messages: Minor Usability Enhancements after v1 release

### ISSUE THREAD

**Issue by kb0rg** [thesis/heimdall#121]
The initial release of the remind command (PR #95) was a first pass. 

We have open issues for major feature enhancements (Issues #45 #60 #61), but before those are tackled there should be some minor usability improvements:
- ~~Improve [datetime syntax help documentation](https://github.com/thesis/heimdall/pull/95#discussion_r324866846)~~
- ~~Add [username to the `[me|team|here]` options](https://github.com/thesis/heimdall/pull/95#pullrequestreview-288878340)~~
- ~~Update [regex pattern](https://github.com/thesis/heimdall/pull/95#discussion_r324869504~~
- More, TBD, as user feedback rolls in

**Comment by Shadowfiend** [comment]
Closing as everything actionable has been implemented here, I believe.
